Update ci-quadlet.yml

diff --git a/.github/workflows/ci-quadlet.yml b/.github/workflows/ci-quadlet.yml
--- a/.github/workflows/ci-quadlet.yml
+++ b/.github/workflows/ci-quadlet.yml
@@ -85,6 +85,9 @@ jobs:
       - name: Set up GOCACHE
         run: export GOCACHE="$(mktemp -d)"
 
+      - name: Check configure.ac file
+        run: test -f configure.ac || echo "configure.ac file not found"
+
       - name: Generate Autotools Files
         run: autoreconf -fi
 
